/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FiltroStatus: typeof import('./src/components/FiltroStatus.vue')['default']
    FormTasks: typeof import('./src/components/FormTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableTask: typeof import('./src/components/TableTask.vue')['default']
  }
}
